
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
